# Generated by Django 2.2.7 on 2019-12-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageAgain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images.jfif', upload_to='blog_images_again/')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
