# Generated by Django 2.2.7 on 2019-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191205_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_summary',
            field=models.TextField(default='blog summary'),
        ),
    ]
